services:
  web:
    image: node:20
    container_name: next_web
    working_dir: /app
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app_network

  api:
    image: python:3.11
    container_name: python_api
    working_dir: /app
    volumes:
      - ./services/api:/app
    ports:
      - "8000:8000"
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - app_network
      
  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongo_container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: QOjmJOG3gUCK2wdvkmDVPZ8r
      MONGO_INITDB_DATABASE: almeria_shop
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_container
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app_network
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_container
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - mongo
      - ollama
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_container
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "5080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - app_network

volumes:
  mongo_data:
  n8n_data:
  ollama_data:
  open-webui_data:
  qdrant_data:

networks:
  app_network:
    driver: bridge